//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.15 at 12:41:43 AM CEST 
//


package replication.prototype.server.environment;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CommunicationEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CommunicationEnumType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="quorum"/>
 *     &lt;enumeration value="async"/>
 *     &lt;enumeration value="sync"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CommunicationEnumType")
@XmlEnum
public enum CommunicationEnumType {

    @XmlEnumValue("quorum")
    QUORUM("quorum"),
    @XmlEnumValue("async")
    ASYNC("async"),
    @XmlEnumValue("sync")
    SYNC("sync");
    private final String value;

    CommunicationEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CommunicationEnumType fromValue(String v) {
        for (CommunicationEnumType c: CommunicationEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
