//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.14 at 10:33:55 PM CEST 
//

package replication.prototype.coordinator.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ReplicationConfigurationType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ReplicationConfigurationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="replicationpaths" type="{http://www.ise.tu-berlin.de/AEC/Prototyping/Replication}ReplicationPathConfigurationType"/>
 *         &lt;element name="replicationnodes" type="{http://www.ise.tu-berlin.de/AEC/Prototyping/Replication}ReplicationNodeConfigurationType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */

// important!: needs to be set by hand
@XmlRootElement(name = "configuration")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReplicationConfigurationType", propOrder = {
		"replicationpaths", "replicationnodes" })
public class ReplicationConfigurationType {

	@XmlElement(required = true)
	protected ReplicationPathConfigurationType replicationpaths;
	@XmlElement(required = true)
	protected ReplicationNodeConfigurationType replicationnodes;

	/**
	 * Gets the value of the replicationpaths property.
	 * 
	 * @return possible object is {@link ReplicationPathConfigurationType }
	 * 
	 */
	public ReplicationPathConfigurationType getReplicationpaths() {
		return replicationpaths;
	}

	/**
	 * Sets the value of the replicationpaths property.
	 * 
	 * @param value
	 *            allowed object is {@link ReplicationPathConfigurationType }
	 * 
	 */
	public void setReplicationpaths(ReplicationPathConfigurationType value) {
		this.replicationpaths = value;
	}

	/**
	 * Gets the value of the replicationnodes property.
	 * 
	 * @return possible object is {@link ReplicationNodeConfigurationType }
	 * 
	 */
	public ReplicationNodeConfigurationType getReplicationnodes() {
		return replicationnodes;
	}

	/**
	 * Sets the value of the replicationnodes property.
	 * 
	 * @param value
	 *            allowed object is {@link ReplicationNodeConfigurationType }
	 * 
	 */
	public void setReplicationnodes(ReplicationNodeConfigurationType value) {
		this.replicationnodes = value;
	}

}
